### ISSUE TITLE
Cross-chain Atomic Swaps between Bitcoin L1/Inscriptions/L2, Ethereum L1/L2/ERC20s

### ISSUE THREAD

**Issue by victorwu** [Portaldefi/mono#142]
# Phase 1: Template Structuring
- [ ] **1.1 Migrate V1 to V2 api**
    - [ ] Update V1 api to follow V2 formatting by Casey, enabling more permutations of swap pairs without needing to run multiple server instances of different versions
    - [ ] have git diff session to see differences between files and how to merge
- [ ] **1.2 Pair-specific Event Ordering and Actions**
    - [ ] Create a system for organizing different sequences of events, specific to each pair. 
      - [x] review keep an inventory of event emitters for better understanding of when events are happening
      - [ ] Server: Move event specification from header in to object passed in body of event
      - [x] Client: ternary filtering based on specified sequence and state (see documentation)
        - [x] refactor to check swap state, instead of reading event headers
      - [ ] E.g. specific ordering of events for ETH L2 to BTC L2, Submarine swaps, ordinal swaps etc.
- [ ] **1.3 Base/Quote Asset Ordering**
    - [ ] Establish a flow for choosing the base and quote asset.
    - [ ] This should include order flows for existing supported pairs like bitcoin lightning to ethereum evm, BTCORD-BTC, with the side ask for swap orders BTCORD base and BTC quote.
      - [ ] Whether or not we should disable the other options if there is no pair, or only show the available pairs to trade?
      - [ ] Client: only display available base / quote asset pairs, depending on what's enabled
        - [ ] add low opacity to non-supported asset options in unsupported pairs, that way users still have the ability to choose a different asset to swap with different pairs
      - [ ] Server: create test cases for different permutations of trades
        - [ ] ordinal to ordinal swap?
        - [ ] reverse swaps?
- [ ] **1.4 Refactor and Split Files**
    - [x] Refactor client.js and split files into core and client for easier management and debugging.
    - [ ] Update swap client importing the client.js from the server code
    - [ ] Add ability for the code to determine which environment it's being used in, to load the right imports for the file
      - [ ] for client
      - [ ] for server

# Phase 2: Documentation Update
- [ ] **2.1 Organize Documentation**
    - [ ] Break down the existing documentation into more manageable parts. Utilize Antora to compile these parts into a single, comprehensive page.
- [x] **2.2 Document Ordinals**
    - [x] Develop a section specifically for ordinals. 
      - [x] This should include a summary of the Ordinal Swap flow
      - [x] details on using taproot for ordinal inscriptions and how to setup different wallets (create new, native segwit, 12 words, then index 1 is submarine, ordinals is 2)
- [x] **2.3 Event sequencing Documentation template**
    - [x] how swap works https://github.com/Portaldefi/mono/pull/56
    - [x] document sequences, states at each step, available actions
      - this way the server doesn't need to keep track of the sequence, we could figure out the step in sequence based on state, easier to search through logs, and client would be validating each step of before proceeding
    - [ ] Discuss: what happens if the ordering of events for a sequence doesn't need to happen in a specific way? 
      - [ ] add advanced steps
- [ ] **2.4 Documentation for Pair-specific intricacies**
    - [x] Each pair should include information about the sequence of events
    - [x] Specific state to be seen at each event
    - [ ] Actions needed to be taken at the next sequence
    - [x] BTCORD-BTC
      - [x] figjam example mapping creating scenarios & happy path, cancellation, tests
        - [ ] figjam for feature mapping
        - [ ] add example mapping for more steps, moving the steps out of cards to expand upon further
      - [ ] update document with Casey's figjam diagram
    - [ ] BTC-ETH
    - [ ] Document game theory intricacies for specific assets and pairs
      - this would also be helpful for understanding all permutations of swaps

# Phase 3: Websockets Improvement
- [ ] **3.1 Websockets**
    - [ ] Test/unit/core/fixtures/index.js to test websocket to minic functions and see if it's returned. 
    - [ ] Add a debounce on websocket open
    - [x] debug subscription to limit the number of open events
    - [x] add cleanup functions to remove extraneous listeners
    - [ ] add serialization of events for ability to watch and clean / close specific events

# Phase 4: Update Testing Suite
- [ ] **4.1 BDD testing**
  - [x] Add support for converting BDD scenarios to tests with cucumber.js
  - [ ] Add tests for EVM
  - [ ] integrate EVM tests into V2 tests
- [ ] **4.2 Integrate Selenium, Jest, and Mock Testing**
    - [x] Implement an automation framework for testing the web application using Selenium and Mock server. 
      - [x] Add selenium for multi-user testing on client ui with mock testing
      - [x] update mock testing to enable ordinals
      - [x] update mock testing to enable ordinals and original v1 swap  
    - [ ] Implement the automation framework for testing with the peer and node. 
      - [ ] update selenium testing with connection to regtest
      - [ ] the mining of blocks
      - [ ] inscribing new ordinal inscriptions
    - [x] Create testing environment for wallets
      - [x] xverse selenium
        - [x] get initial address from preloaded seed
        - [x] load in chrome profile and set seed
      - [x] alby selenium
        - [x] get initial address from preloaded seed
        - [x] load in chrome profile and set seed
      - [x] unisat selenium
        - [x] get initial address from preloaded seed
        - [x] load in chrome profile and set seed
      - [x] metamask selenium
        - [ ] check with puppeteer
        - [ ] webdriver
        - [x] fork metamask and remove section that blocks automated browser actions
- [ ] **4.3 Regtest & Mining Blocks**
    - [ ] Test with regtest, mining blocks, and inscribing for understanding the current performance and identifying potential areas for improvement.
- [x] **4.3 Review Code for Event Emitters**
    - [x] Perform a code review to take inventory of the event emitters. Identify opportunities for optimization and note any areas for potential error correction.

# Phase 5: Multi-Chain Wallets
- [ ] **5.1 Credentials Sharing to the Server**
    - [ ] Establish a secure method for sharing credentials with the server. This should consider best practices for security and encryption.
    - [ ] Pass credentials through header of api calls
    - [ ] Chain by chain implementation
- [ ] **5.2 Multi-chain Connect**
  - [ ] create a checker for each pair that requires relevant wallets to be connected before creating a swap
    - [x] Implement a feature to connect with multiple chains like bitcoin/lightning, unisat, bitmask, alby, joule etc.
      - [ ] https://socket.dev/npm/package/alby-js-sdk/overview/1.7.1
      - [x] integrate Alby
        - [x] create test invoices
        - [x] test signing feature
        - [ ] connect with regtest
    - [ ] Look for another wallet instead of alby as it does not work with hodl invoices
    - [ ] Wallet should have ability to use own network settings, open source, access to bitcoin L1 and lightning credentials
- [x] **5.3 Integrate Bitcoin L1 taproot wallet**
    - [x] Resolve the bitmask and CORS issues that are currently causing the application not to work in the browser.
      - bitmask developers have yet to launch a working product
    - [x] Integrate Bitmask JS to the application.
      - [x] check discord: mentioned it is still pending launch
    - [x] integrate Xverse
      - [x] simulate a test transaction
    - [x] Integrate Unisat
        - [x] Integrate Unisat and see how regtest could be integrated.
- [ ] **5.4 Integrate Lighting wallet**
    - [x] Integrate lightning wallet to the wallet connection
    - [ ] Casey & Anand to look into peer for lightning, some ideas:
      - [ ] Voltage
      - [ ] lightning network connect
      - [ ] sensei
- [ ] **5.5 Integrate Nosft btc wallet and collections implementation**
    - [ ] Integrate ability to generate bitcoin taproot addresses using hints from nosft
    - [ ] https://github.com/topether21/nosft-fork

# Phase 6 Credentials on client side
- [ ] remove credentials from server side
- [ ] move credential management and signing-specific actions to client side
- [ ] Discuss: what are the steps needed to move the credentials out of the server?
  - [ ] what messages would be moved to the client side and need to be signed? 
- [ ] Discuss swapping between multiple roles, instead of only Alice & Bob, how about adding Carol 
  - current implementation is only swapping between two roles, but we can't add Charlie
  - because Alice & Bob are hardcoded, then all we could do is just Alice and Bob
- [ ] Discuss: how to manage when client is offline midway through a swap

# Phase 7: Miscellaneous Tasks
- [ ] **6.1 API Integration**
    - [ ] Get the tokenrank API working with the system for more diverse and accurate data.
    - [ ] integrate available pair types
      - [ ] include sequencing of events for specific pair types
- [ ] **6.2 Minor Improvements**
    - [x] Update padding input instead of hardcoding
    - [x] adding/removing the asset back to the list after swap
      - [ ] should show up on Bob's wallet and removed from Alice's, & vice versa
    - [ ] create a list of inscriptions for each user in the asset tab.
    - [x] update inscription naming so base network is consistent 
    - [ ] adding custom inscription location for creating a new swap order (under the inscription collections list)
      - [ ] UI custom quote asset input box for inscription location, @arteepa 
    - [ ] separate Alice & Bob's list of inscriptions, match list of inscriptions for each signed-in user
- [ ] **6.3 Ordinal standardization**
    - [ ] Integrate Ordinal API to view inscriptions of a user
      - [ ] check hiro ordinal api https://www.hiro.so/blog/introducing-the-ordinals-explorer-and-ordinals-api
        - [ ] https://github.com/hirosystems/ordinals-api
        - [ ] https://docs.hiro.so/ordinals
- [ ] Discuss channel factories and DLCs (Casey)
