### ISSUE TITLE
P2P V0 Testnet Launch Checklist (single node)

### ISSUE THREAD

**Issue by manojdv** [Portaldefi/mono#224]
We need to release the Alpha version of swap client with the following requirements:

### **Phase 1 Improvements**

- Coordinator
  - [x] Order Management - order execution engine
  - [x] Swap Management - create a swap from a pair of matched orders

- Peer
  - [ ] Peer Initialization - a step-by-step wizard to setup the peer for regular operation
    - [ ] UI-based wizard for regular users
    - [ ] Terminal-based wizard for power-users
  - [ ] Peer Operation - regular operation of the peer
    - [ ] Wallet Management
      - [ ] Get wallet balance
      - TBD...
    - [x] Order Management
      - [x] Newly-placed orders are persisted in the local store, and forwarded to the coordinator for execution.
      - [x] Cancelled orders are forwarded to the coordinator for cancellation, and removed from the local store
      - [x] Fire events, as necessary, to notify any connected clients
    - [x] Swap Management
      - [x] Follow the steps of an atomic swap to progress through the various states until the assets are swapped.
      - [x] Fire events, as necessary, to notify any connected clients

- SDK
  - [ ] Break out SDK into three flavors:
    - [x] `browser` to handle communications between the `peer` and browser-based applications
    - [x] `node` to handle communications between the `peer` and node.js applications
    - [ ] `p2p` communications between the `peer` and the `coordinator`, with future scope to extend to direct communications between `peer` instances.
  - [ ] Publish minified version of SDK

- UI Development
  - [ ] Implement UX for confirmations (@victorwu, @arteepa)
  - [ ] Add client side analytics (@victorwu, @anandsuresh)

- Supported Chains/Networks (@anandsuresh, @casey-bowman, @melnx)
  - [ ] Support 2 way swaps (@anandsuresh)
  - [ ] ERC20 support (@victorwu)
  - [ ] Code cleanup and refactor

### **Phase 2 Improvements**

- Operations
  - [ ] Add log monitoring service
  - [ ] Add License to Github repo (BSUL, from Heath)

- Add EVMOS node to PortalOS 
   - [ ] Use EVMOS node as part of PortalOS
   - [ ] Add Swap intents and swap objects into EVMOS (migrate existing storage into emvos node or replicate storage inside the node storage)
   - [ ] Swaps are broadcast and gossiped to other nodes
   - [ ] Create a Blockexplorer for portalOS (to track swaps, other nodes, in phase 3 pools)

- Trading Bots
  - [ ] Implement a bot trader to be a counterparty
  - [ ] Testnet trading bot
  
- PortalOS
  - [ ] Ability to mix and match swaps across above chains

- Browser Extension
  - [x] #218
  - [ ] Code cleanup and refactor

- Documentation (@anandsuresh)
  - [ ] Add documentation in the form of Markdown/AsciiDoc
  - [ ] Add build process to produce HTML/PDF/any other format for documentation
  - [ ] Code cleanup and refactor

- Supported Chains
  - [ ] Arbitrum
  - [ ] Bitcoin L1
  - [ ] Bitcoin Ordinals (@casey-bowman)
